# Generated by Django 3.2.5 on 2021-07-30 06:30

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='DailyMontage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type', models.CharField(choices=[('Montaż', 'Montaż'), ('Reklamacja', 'Reklamacja'), ('Montaż + Reklamacja', 'Montaż + Reklamacja'), ('Capacity', 'Capacity')], default='Montaż', max_length=35)),
                ('day_montage', models.CharField(choices=[('1/1', '1/1'), ('1/2', '1/2'), ('2/2', '2/2'), ('1/3', '1/3'), ('2/3', '2/3'), ('3/3', '3/3')], default='1/1', max_length=8)),
                ('date', models.DateField()),
                ('created', models.DateTimeField(editable=False)),
                ('updated', models.DateTimeField()),
            ],
        ),
        migrations.CreateModel(
            name='Monter',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=15)),
                ('created', models.DateTimeField(editable=False)),
                ('updated', models.DateTimeField()),
            ],
        ),
        migrations.CreateModel(
            name='Team',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('team', models.CharField(max_length=15, unique=True)),
                ('created', models.DateField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='MonterDaily',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(choices=[('PRACUJE', 'PRACUJE'), ('L4', 'L4'), ('URLOP', 'URLOP')], default='PRACUJE', max_length=30)),
                ('time_start', models.TimeField(blank=True, null=True)),
                ('end_time', models.TimeField(blank=True, null=True)),
                ('daily_hours', models.TimeField(blank=True, null=True)),
                ('date', models.DateField()),
                ('created', models.DateTimeField(editable=False)),
                ('updated', models.DateTimeField()),
                ('daily_montage', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='core.dailymontage')),
                ('name', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='core.monter')),
            ],
        ),
        migrations.CreateModel(
            name='MontagePaid',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('days', models.CharField(choices=[('Jednodniówka', 'Jednodniówka'), ('Dwudniówka', 'Dwudniówka'), ('Trzydniówka', 'Trzydniówka')], default='Jednodniówka', max_length=30)),
                ('date', models.DateField()),
                ('paid', models.PositiveSmallIntegerField(default=0)),
                ('cabinet', models.PositiveSmallIntegerField(default=0)),
                ('comment', models.TextField(blank=True, null=True)),
                ('build', models.BooleanField(default=False)),
                ('cornice', models.BooleanField(default=False)),
                ('turnbuckles', models.SmallIntegerField(default=1)),
                ('type_table', models.CharField(max_length=40)),
                ('created', models.DateTimeField(editable=False)),
                ('updated', models.DateTimeField()),
                ('montage', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.dailymontage')),
            ],
        ),
        migrations.AddField(
            model_name='dailymontage',
            name='team',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='core.team'),
        ),
        migrations.AddField(
            model_name='dailymontage',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddConstraint(
            model_name='monterdaily',
            constraint=models.UniqueConstraint(fields=('name', 'date'), name='name of monter work'),
        ),
        migrations.AddConstraint(
            model_name='montagepaid',
            constraint=models.UniqueConstraint(fields=('montage', 'created'), name='name of montage paid'),
        ),
        migrations.AddConstraint(
            model_name='dailymontage',
            constraint=models.UniqueConstraint(fields=('team', 'created'), name='name of daily montage'),
        ),
    ]
