# Generated by Django 3.2.5 on 2021-07-30 19:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_auto_20210730_2132'),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name='dailymontage',
            name='name of daily montage',
        ),
        migrations.RemoveConstraint(
            model_name='montagepaid',
            name='name of montage paid',
        ),
        migrations.AddConstraint(
            model_name='dailymontage',
            constraint=models.UniqueConstraint(fields=('team', 'date'), name='name of daily montage'),
        ),
        migrations.AddConstraint(
            model_name='montagepaid',
            constraint=models.UniqueConstraint(fields=('montage', 'date'), name='name of montage paid'),
        ),
    ]
