# Generated by Django 3.2.5 on 2021-07-31 12:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_auto_20210730_2136'),
    ]

    operations = [
        migrations.AlterField(
            model_name='dailymontage',
            name='day_montage',
            field=models.CharField(choices=[('1/1', 'Jeden dzień - 1/1'), ('1/2', 'Jeden z dwóch dni - 1/2'), ('2/2', 'Drugi dzień z dwudniówki - 2/2'), ('1/3', 'Jeden z trzech dni - 1/3'), ('2/3', 'Drugi z trzech dni - 2/3'), ('3/3', 'Trzeci dzien z trzydniówki - 3/3')], default='1/1', max_length=8),
        ),
        migrations.AlterField(
            model_name='monterdaily',
            name='status',
            field=models.CharField(choices=[('PRACUJE', 'PRACUJE'), ('L4', 'L4'), ('URLOP', 'URLOP')], default='PRACUJE', max_length=30, null=True),
        ),
    ]
