# Generated by Django 3.2.5 on 2021-07-31 12:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0004_auto_20210731_1441'),
    ]

    operations = [
        migrations.AlterField(
            model_name='monterdaily',
            name='status',
            field=models.CharField(blank=True, choices=[('PRACUJE', 'PRACUJE'), ('L4', 'L4'), ('URLOP', 'URLOP')], default='PRACUJE', max_length=30, null=True),
        ),
    ]
