# Generated by Django 3.2.5 on 2021-07-31 18:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0005_alter_monterdaily_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='montagepaid',
            name='status',
            field=models.CharField(choices=[('WYKONANE', 'WYKONANE'), ('NIEWYKONANE', 'NIEWYKONANE + DODAJ KOMENTARZ')], default='WYKONANE', max_length=50),
        ),
    ]
