# Generated by Django 3.2.5 on 2021-08-05 04:52

import core.models
from django.db import migrations
import sorl.thumbnail.fields


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0008_montagegallery_user'),
    ]

    operations = [
        migrations.AlterField(
            model_name='montagegallery',
            name='images',
            field=sorl.thumbnail.fields.ImageField(blank=True, null=True, upload_to=core.models.montage_gallery_path),
        ),
    ]
