# Generated by Django 3.2.5 on 2021-08-10 19:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0009_alter_montagegallery_images'),
    ]

    operations = [
        migrations.AddField(
            model_name='monter',
            name='type',
            field=models.CharField(choices=[('MONTAŻ', 'MONTAŻ'), ('REKLAMACJA', 'REKLAMACJA')], default='MONTAŻ', max_length=15),
        ),
        migrations.AlterField(
            model_name='dailymontage',
            name='type',
            field=models.CharField(choices=[('Montaż', 'Montaż'), ('Reklamacja', 'Reklamacja'), ('Montaż + Reklamacja', 'Montaż + Reklamacja'), ('Capacity', 'Capacity'), ('Prywatne', 'Prywatne')], default='Montaż', max_length=35),
        ),
    ]
