# Generated by Django 3.2.5 on 2021-08-31 13:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0011_alter_monterdaily_daily_montage'),
    ]

    operations = [
        migrations.AlterField(
            model_name='monterdaily',
            name='status',
            field=models.CharField(blank=True, choices=[('PRACUJE', 'PRACUJE'), ('L4', 'L4'), ('URLOP', 'URLOP'), ('UŻ', 'UŻ'), ('NB', 'NB')], default='PRACUJE', max_length=30, null=True),
        ),
    ]
