# Generated by Django 3.2.5 on 2021-11-12 08:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0012_alter_monterdaily_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='montagepaid',
            name='status',
            field=models.CharField(choices=[('WYKONANE', 'WYKONANE'), ('NIEWYKONANE', 'NIEWYKONANE + DODAJ KOMENTARZ'), ('ZRZUTKA', 'ZRZUTKA + PODAJ POWÓD')], default='WYKONANE', max_length=50),
        ),
    ]
