# Generated by Django 3.2.5 on 2021-12-02 07:18

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('geotask', '0003_task_monters'),
        ('core', '0013_alter_montagepaid_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='monterdaily',
            name='geotask',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='geotask', to='geotask.task'),
        ),
        migrations.AlterField(
            model_name='monterdaily',
            name='daily_montage',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='daily_montage', to='core.dailymontage'),
        ),
    ]
