# Generated by Django 3.2.5 on 2022-01-05 20:25

import core.models
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import video_encoding.fields


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('core', '0015_auto_20211205_1747'),
    ]

    operations = [
        migrations.CreateModel(
            name='MontageVideoGallery',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('width', models.PositiveIntegerField(editable=False, null=True)),
                ('height', models.PositiveIntegerField(editable=False, null=True)),
                ('duration', models.FloatField(editable=False, null=True)),
                ('file', video_encoding.fields.VideoField(height_field='height', upload_to=core.models.montage_video_path, width_field='width')),
                ('date', models.DateField(auto_now_add=True)),
                ('montage', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.montagepaid')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
