# Generated by Django 3.2.5 on 2022-01-15 11:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0017_auto_20220115_1255'),
    ]

    operations = [
        migrations.AddField(
            model_name='montagevideogallery',
            name='duration',
            field=models.FloatField(editable=False, null=True),
        ),
        migrations.AddField(
            model_name='montagevideogallery',
            name='height',
            field=models.PositiveIntegerField(editable=False, null=True),
        ),
        migrations.AddField(
            model_name='montagevideogallery',
            name='width',
            field=models.PositiveIntegerField(editable=False, null=True),
        ),
    ]
