# Generated by Django 3.2.5 on 2021-08-31 13:47

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('core', '0012_alter_monterdaily_status'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Todo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(choices=[('ZGŁOSZONA', 'ZGŁOSZONA'), ('KONTAKT', 'KONTAKT'), ('UMÓWIONA', 'UMÓWIONA'), ('WYKONANA', 'WYKONANA'), ('NIEWYKONANA', 'NIEWYKONANA')], default='ZGŁOSZONA', max_length=30)),
                ('created', models.DateTimeField(editable=False)),
                ('updated', models.DateTimeField()),
                ('team', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.team')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
