# Generated by Django 3.2.5 on 2021-08-31 19:57

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('core', '0012_alter_monterdaily_status'),
    ]

    operations = [
        migrations.CreateModel(
            name='Todo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('uuid', models.CharField(default=uuid.uuid4, editable=False, max_length=150)),
                ('status', models.CharField(choices=[('ZGŁOSZONA', 'ZGŁOSZONA'), ('KONTAKT', 'KONTAKT'), ('UMÓWIONA', 'UMÓWIONA'), ('WYKONANA', 'WYKONANA'), ('NIEWYKONANA', 'NIEWYKONANA')], default='ZGŁOSZONA', max_length=30)),
                ('title', models.CharField(default=None, max_length=80)),
                ('desc', models.TextField(default=None)),
                ('contact_date', models.DateField(null=True)),
                ('date', models.DateField(null=True)),
                ('finish_date', models.DateField(null=True)),
                ('created', models.DateTimeField(editable=False)),
                ('updated', models.DateTimeField()),
                ('team', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.team')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='ToDoHistory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(choices=[('ZGŁOSZONA', 'ZGŁOSZONA'), ('KONTAKT', 'KONTAKT'), ('UMÓWIONA', 'UMÓWIONA'), ('WYKONANA', 'WYKONANA'), ('NIEWYKONANA', 'NIEWYKONANA')], default='ZGŁOSZONA', max_length=30)),
                ('old_status', models.CharField(choices=[('ZGŁOSZONA', 'ZGŁOSZONA'), ('KONTAKT', 'KONTAKT'), ('UMÓWIONA', 'UMÓWIONA'), ('WYKONANA', 'WYKONANA'), ('NIEWYKONANA', 'NIEWYKONANA')], default='ZGŁOSZONA', max_length=30)),
                ('created', models.DateTimeField(editable=False)),
                ('updated', models.DateTimeField()),
                ('todo', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='todo.todo')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
