# Generated by Django 3.2.5 on 2021-11-12 08:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('todo', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='todo',
            name='is_urgent',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='todo',
            name='status',
            field=models.CharField(choices=[('ZGŁOSZONA', 'ZGŁOSZONA'), ('UMÓWIONA', 'UMÓWIONA'), ('W TRAKCIE', 'W TRAKCIE'), ('WYKONANA', 'WYKONANA')], default='ZGŁOSZONA', max_length=30),
        ),
        migrations.AlterField(
            model_name='todohistory',
            name='old_status',
            field=models.CharField(choices=[('ZGŁOSZONA', 'ZGŁOSZONA'), ('UMÓWIONA', 'UMÓWIONA'), ('W TRAKCIE', 'W TRAKCIE'), ('WYKONANA', 'WYKONANA')], default='ZGŁOSZONA', max_length=30),
        ),
        migrations.AlterField(
            model_name='todohistory',
            name='status',
            field=models.CharField(choices=[('ZGŁOSZONA', 'ZGŁOSZONA'), ('UMÓWIONA', 'UMÓWIONA'), ('W TRAKCIE', 'W TRAKCIE'), ('WYKONANA', 'WYKONANA')], default='ZGŁOSZONA', max_length=30),
        ),
    ]
