# Generated by Django 3.2.5 on 2021-11-12 08:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('todo', '0002_auto_20211112_0926'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='todo',
            name='is_urgent',
        ),
    ]
