# Generated by Django 3.2.5 on 2021-11-24 07:14

import django.core.validators
from django.db import migrations, models
import geotask.models


class Migration(migrations.Migration):

    dependencies = [
        ('geotask', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='project',
            name='file',
            field=models.FileField(blank=True, null=True, upload_to=geotask.models.projects_path, validators=[django.core.validators.FileExtensionValidator(['pdf'])]),
        ),
    ]
