# Generated by Django 3.2.5 on 2021-11-25 07:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0013_alter_montagepaid_status'),
        ('geotask', '0002_alter_project_file'),
    ]

    operations = [
        migrations.AddField(
            model_name='task',
            name='monters',
            field=models.ManyToManyField(to='core.Monter'),
        ),
    ]
