# Generated by Django 3.2.5 on 2021-12-03 16:40

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('geotask', '0004_alter_commenttask_comment'),
    ]

    operations = [
        migrations.AlterField(
            model_name='commenttask',
            name='task',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='geotask.task'),
        ),
    ]
